chaines_tv = [
    "TF1",
    "France 2",
    "France 3",
    "Canal+",
    "France 5",
    "M6",
    "Arte",
    "C8",
    "W9",
    "TMC",
    "TFX",
    "NRJ 12",
    "LCP",
    "France 4",
    "BFMTV",
    "CNews",
    "CStar",
    "Gulli",
    "France Ô",
    "TF1 Séries Films",
    "L'Équipe",
    "6ter",
    "RMC Story",
    "RMC Découverte",
    "Chérie 25",
    "LCI",
    "France Info",
    "TV5 Monde",
    "M6 Music",
    "MCM",
    "Game One",
    "Comédie+",
    "Téva",
    "Paris Première",
    "RTL9",
    "AB1",
    "Eurosport 1",
    "Eurosport 2",
    "TF1 +1",
    "France 2 +1",
    "BFMTV +1",
    "LCI +1",
    "Gulli +1",
    "France Ô +1",
    "Arte +1",
    "TF1 Séries Films +1",
    "RMC Story +1",
    "RMC Découverte +1",
    "Chérie 25 +1",
    "L'Équipe +1",
    "6ter +1",
    "Canal+ Sport",
    "Canal+ Cinéma",
    "Canal+ Séries",
    "Canal+ Family",
    "Canal+ Décalé",
    "Canal+ Sport +1",
    "Canal+ Cinéma +1",
    "Canal+ Séries +1",
    "Canal+ Family +1",
    "Canal+ Décalé +1",
    "RMC Sports"
]

for chaine in chaines_tv:
    print(chaine)
    if chaine == "RMC Sports":
        break